var i18n = {
thousands_sep: ',',
'Enter version name': 'Geben Sie einen Namen für die Version ein',
'Unable to load images: ': 'Kann Bilder nicht laden: ',
'Name field is empty': 'Sie müssen einen Namen eingeben',
'Text field is empty': 'Sie müssen einen Text eingeben',
'Enter ID for new zone': 'Geben Sie die ID für die neue Zone ein',
'Enter name for new zone': 'Geben Sie den Namen der neuen Zone ein',
'Really delete zone?': 'Sind Sie sicher, dass diese Zone gelöscht wird ?',
'Enter name for new design': 'Geben Sie den Namen des neuen Design ein',
'Unable to create design: ': 'Kann Design nicht anlegen: ',
'Unable to load design list: ': 'Designliste konnte nicht geladen werden: ',

'Condition: ': 'Zustand: ',
'Actions if True: ': 'Eingeschaltet: ',
'Actions if False: ': 'Ausgeschaltet: ',
'on weekdays ': 'An Werktagen ',
'only on exception days ': 'nur an bestimmten Tagen ',
'except on exception days ': 'Ausnahmen an bestimmten Tagen ',
'at ': 'Im ',
'until ': 'Bis ',
'every ': 'immer ',
'during ': 'Während ',
' seconds': ' Sekunde',
' weekdays ': ' Werktags ',
'Set object': 'Setze Objekt',
'to': 'zu',
"Dim object '": "Dimmer Objekt '",
"' from ": "' von ",
" to ": " zu ",
" during ": " Während ",
"Send SMS '": "Sende SMS '",
"' to ": "' zu ",
"Send Email with subject '": "Sende Email mit Betreff '",
"Cycle object '": "Ändere Object '",
"' ON for ": "' AN für ",
" sec and OFF for ": " AUS für ",
" sec ": " Sekunde ",
" times": " Mal",
" (stop condition: ": " (stope Bedingung: ",
"Execute shell command '": "Shell-Befehl ausführen '",

'Error: ': 'Fehler: ',
'Error while saving design: ': 'Kann Design nicht speichern: ',
"Error while loading rules: ": "Kann Regeln nicht laden: ",
'Design saved successfully': 'Design erfolgreich gespeichert',
'Cancel': 'Abbrechen',
'Ok': 'Ok',
'Add': 'Hinzufügen',
'Close': 'Schließen',

'Design': 'Design',
'Modify layout': 'Zuweisung ändern',
'Save design': 'Design speichern',
'Display design (XML)': 'Design anzeigen (XML)',
'Design list': 'Designliste',
'Display design': 'Design anzeigen',
'Modify design': 'Design bearbeiten',
'Display rules': 'Regeln anzeigen',
'Grid: ': 'Raster: ',

'Zones': 'Zonen',
'Modify background': "Bild ändern",
'Background selection': "Bild wählen",

'New switch': 'Neuer Schalter',
'New dimmer': 'Neuer Dimmer',
'New thermostat': 'Neues Thermostat',
'New goto': 'Neuer Sprung',
'New camera': 'Neue Kamera',
'New text': 'Neuer Text',
'Image type:': 'Icon Auswahl:',
'light': 'Licht',
'outlet': 'Steckdose',
'fan': 'Ventilator',
'pump': 'Pumpe',
'blinds': 'Jalousie',
'ReadOnly:': 'Nur anzeigen:',

'Insert value:': 'Werte hinzufügen:',
'Offset:': 'Wertpositionierung:',
'Object:': 'Objekt:',
'custom': 'Benutzerdefiniert',
'Image On:': 'Bild für AN:',
'Image Off:': 'Bild für AUS:',
'Pattern:': 'Anordnung:',

'New scale': 'Neue Anpassung',
'left': 'Links',
'right': 'Rechts',
'upper': 'Hoch',
'lower': 'Runter',
'Image File:': 'Bild-Datei:',
'Image file:': 'Bild-Datei:',
'Width:': 'Breite:',
'Height:': 'Höhe:',
'Steps:': 'Schritte:',
'Vertical shift:': 'Vertikale Verschiebung:',
'Horizontal shift:': 'Horizontale Verschiebung:',

'New value input': 'Neue Werteingabe',
'New multiswitch': 'Neuer Multi-Schalter',
'Value:': 'Wert:',
'Number of items:': 'Anzahl Darstellungen:',

'New HTML block': 'Neue HTML Seite',
'HTML Code:': 'HTML Code:',
'Format:': 'Format:',
'800 x 600': '800 x 600',
'1024 x 768': '1024 x 768',
'1280 x 960': '1280 x 960',
'1400 x 1050': '1400 x 1050',
'Homeserver': 'Homeserver',
'Demo': 'Demo',
'PDA': 'PDA',

'Name:': 'Name:',
'Command object:': 'Auswahl:',
'On/Off command object:': 'Auswahl An/Aus:',
'Up/Down command object:': 'Auswahl Hoch/Runter:',
'Value object:': 'Statusanzeige:',
'Cam picture URL:': "Url vom Bild:",
'Mode object:': 'Modus:',
'Setpoint object:': 'Soll-Temp:',
'Current temp. object:': 'Ist-Temp:',
'Go to:': 'Nach:',
'Image:': 'Bild:',
'Text:': 'Text:',
'Style:': 'Stil:',
'Setpoint: ': 'Soll-Temp: ',
'Temp: ': 'Ist-Temp.: ',
'Mode: ': 'Modus: ',
'comfort': 'Komfort',
'standby': 'Standby',
'night': 'Nacht',
'frost': 'Frostschutz',
'': ''
};