var i18n = {
thousands_sep: ',',
'Enter version name': 'Entrez un nom de version',
'Unable to load images: ': 'Impossible de charger les images',
'Name field is empty': 'Vous devez spécifier un nom',
'Text field is empty': 'Vous devez entrer le texte',
'Enter ID for new zone': 'Entrez l\'ID de la nouvelle zone',
'Enter name for new zone': 'Entrez le nom de la nouvelle zone',
'Really delete zone?': 'Etes-vous sûr de vouloir supprimer cette zone?',
'Enter name for new design': 'Entrez le nom du nouveau design',
'Unable to create design: ': 'Impossible de créer le design: ',
'Unable to load design list: ': 'Impossible de charger la liste des design: ',

'Condition: ': 'Condition: ',
'Actions if True: ': 'Actions si Vrai: ',
'Actions if False: ': 'Actions si Faux: ',
'on weekdays ': 'les jours de la semaine ',
'only on exception days ': 'seulement les jours d\'exception ',
'except on exception days ': 'sauf les jours d\'exception ',
'at ': 'à ',
'until ': 'jusque ',
'every ': 'toutes les ',
'during ': 'pendant ',
' seconds': ' secondes',
' weekdays ': ' les jours de la semaine ',
"Set object '": "Positionner l'objet '",
"' to '": "' à '",
"Dim object '": "Dimmer l'objet '",
"' from ": "' de ",
" to ": " jusque ",
" during ": " pendant ",
"Send SMS '": "Envoyer SMS '",
"' to ": "' à ",
"Send Email with subject '": "Envoyer e-mail avec le sujet '",
"Cycle object '": "Actionner périodiquement l'objet '",
"' ON for ": "' ON durant ",
" sec and OFF for ": " secondes et OFF durant ",
" sec ": " secondes ",
" times": " fois",
" (stop condition: ": " (condition d'arrêt: ",
"Execute shell command '": "Executer la commande shell '",

'Error: ': 'Erreur: ',
'Error while saving design: ': 'Erreur lors de la sauvegarde du design: ',
"Error while loading rules: ": "Erreur lors du chargement des règles: ",
'Design saved successfully': 'Design sauvegardé avec succès',
'Cancel': 'Annuler',
'Ok': 'Ok',
'Add': 'Ajouter',

'Design': 'Design',
'Modify layout': 'Modifier la disposition',
'Save design': 'Sauver le design',
'Display design (XML)': 'Afficher le design (XML)',
'Design list': 'Liste des design',
'Display design': 'Afficher le design',
'Modify design': 'Modifier le design',
'Display rules': 'Afficher les règles',
'Grid: ': 'Grille: ',

'Zones': 'Zones',
'Modify background': "Modifier l'image",
'Background selection': "Sélection de l'image de fond",

'New switch': 'Nouveau switch',
'New dimmer': 'Nouveau dimmer',
'New thermostat': 'Nouveau thermostat',
'New goto': 'Nouveau saut',
'New camera': 'Nouvelle camera',
'New text': 'Nouveau texte',
'Image type:': "Type d'Icone:",
'light': 'lumière',
'outlet': 'prise',
'fan': 'ventilateur',
'pump': 'pompe',
'blinds': 'volets',
'ReadOnly:': 'Lecture seule:',

'Insert value:': 'Insérer valeur:',
'Offset:': 'Position:',
'Object:': 'Objet:',
'custom': 'Autre...',
'Image On:': 'Image allumé:',
'Image Off:': 'Image éteint:',
'Pattern:': 'Modèle:',

'New scale': 'Nouvelle position',
'left': 'gauche',
'right': 'droite',
'upper': 'haut',
'lower': 'bas',
'Image File:': 'Fichier image:',
'Image file:': 'Fichier image:',
'Width:': 'Largeur:',
'Height:': 'Hauteur:',
'Steps:': 'Pas:',
'Vertical shift:': 'Décalage vertical:',
'Horizontal shift:': 'Décalage Horizontal:',

'New HTML block': 'Nouveau bloc HTML',
'HTML Code:': 'Code HTML:',

'Name:': 'Nom:',
'Command object:': 'Objet de commande:',
'On/Off command object:': 'Objet de commande On/Off:',
'Up/Down command object:': 'Commande haut/bas:',
'Value object:': 'Objet de valeur absolue:',
'Cam picture URL:': "URL de l'image:",
'Mode object:': 'Objet de changement de mode:',
'Setpoint object:': 'Objet de consigne:',
'Current temp. object:': 'Objet de temperature actuelle:',
'Go to:': 'Vers:',
'Image:': 'Image:',
'Text:': 'Texte:',
'Style:': 'Style:',
'Setpoint: ': 'Consigne: ',
'Temp: ': 'Température: ',
'Mode: ': 'Mode: ',
'comfort': 'Confort',
'standby': 'Eco',
'night': 'Nuit',
'frost': 'Protection gel',
'': ''
};